### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by balmha**
add php73-php-ldap and php73-php-zip to Dockerfile

## Status
READY

## Description
Add needed packages to deploy ldap in ocs v2.8 auth

### CODE REVIEW

**Comment by Neustradamus** [comment]
Any news about this PR?

**Comment by gillesdubois** [comment]
Thanks for bringing back this PR. It slipped out of my mind :)

I'm merging.

**Comment by balmha** [comment]
Thxx!!. When this fork is updated in docker hub?

**Comment by Neustradamus** [comment]
@gillesdubois: Thanks!

**Pull request merged**
